spring:
  application:
    name: SmartLogiV2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/okta"
        provider:
          okta:
            issuer-uri: ${ISSUER_URI}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /api-docs
    operations-sorter: method

logging:
  level:
    root: WARN
  file:
    name: app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

security:
  jwt:
    secret-key: ${SECRET_KEY}
    expiration-time: 3600000

server:
  port: 8080